# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 183fc13dc95e285a66b9d3ef8f5c73016cadb2706fb22d40cddee5ad7658e80c818e565cb3c5bc948c483b749d2e95b4b6d9082cb661fc3fb026245a35dd53d0

test:
  secret_key_base: f4de37f10ce65b5ebf3bc0a8e7bc4968aa3bed005ed826c786e77b11ff98878a53b0c64fc1c215b01fb7ca74e034e6e3f7d569fa422647265b0be23f098c74de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
